version: '3'
services:
  node_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: calculator-bot
    container_name: calculator_bot
    restart: always
    ports:
      - "3001:3000"        
    depends_on:
      - mongo_db
    volumes:
      - ./server:/usr/src/app/server    
    networks:
      - app_network

  mongo_db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"       
    volumes:
      - mongodb_data:/data/db 
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:  
