version: '3'
services:
  node_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: calculator-bot_server
    container_name: calculator_bot_server
    restart: always
    ports:
      - "3001:3000"        
    depends_on:
      - mongo_db
    volumes:
      - ./server:/usr/src/app/server    
    networks:
      - app_network
  react_app:
    build:
      context: ./client 
      dockerfile: Dockerfile
    image: calculator-bot_client
    container_name: calculator-bot_client
    restart: always
    ports:
      - "3002:3000" 
    volumes:
      - ./client:/usr/src/app/client    
    networks:
      - app_network
  mongo_db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"       
    volumes:
      - mongodb_data:/data/db 
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:  
